#!/bin/bash
echo "Starting Prometheus and Grafana monitoring stack..."
echo ""
echo "This will start:"
echo "- Prometheus on http://localhost:9090"
echo "- Grafana on http://localhost:3001 (admin/admin123)"
echo ""
echo "Make sure your Spring Boot application is running on port 8080"
echo ""
read -p "Press Enter to continue..."
docker-compose up -d
echo ""
echo "Monitoring stack started!"
echo ""
echo "Access URLs:"
echo "- Prometheus: http://localhost:9090"
echo "- Grafana: http://localhost:3001 (admin/admin123)"
echo ""
echo "To stop the monitoring stack, run: docker-compose down"
read -p "Press Enter to exit..."
